#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
# bspc config window_gap          12

# bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a mpv state=floating
bspc rule -a virt-manager desktop=3

# Autostart
feh --bg-fill ~/pictures/wallpapers/gritty.png &
xset r rate 210 40
setxkbmap -layout us,ar -option grp:alt_shift_toggle
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# nm-applet --indecator &
bspwmbar
